Session Table
timclark97/photo-app pull request #1
Opened 2024-01-06 23:45 UTC by cstrayer24

2024-01-07 00:55 UTC, timclark97 requested changes
Nice work. Left comments. Two other things.

1. Consistent code style is important when working on a project with multiple people. I have prettier set up for the repo to achieve this. To use it, just install the prettier extension in VS code and save the file. It should auto format it for you You should also install all the other recommended extensions for the repo.
2. When making changes to the database, your PR should include the migration sql file. So generate that and push it up.

2024-01-07 00:55 UTC, timclark97 commented on apps/api/src/sharedData/dates.ts
> +export const weekFromNow =  new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 7)
I like the idea here, but since this is only being used in 1 place right now, creating this directory and file is not needed. Once the code base is bigger and more code reuse is happening, doing something like this will make sense. But not worth prematurely solving a problem we dont have yet.

2024-01-07 00:55 UTC, timclark97 commented on apps/api/src/components/Session/SessionSchema.ts
> +    user_id:uuid("user_id").references(()=>users.id,{onDelete:"cascade"}).notNull(),
Good job defining the foreign key here, this establishes the relationship between the tables at the database level. But we still need to define the relationship at the ORM level. With drizzle, that is done with [relations](https://orm.drizzle.team/docs/rqb#declaring-relations). Set one up between users and sessions.

2024-01-09 02:35 UTC, timclark97 commented on apps/api/src/components/Session/SessionSchema.ts
> +    .default(weekFromNow)
I just realized that this is not behaving the way you are intending. The `.default()` method converts the input in to sql. So here it is evaluating the function at run time and setting the column default to be whatever the return of the function is. We cannot set a default for this column via sql. We will have to set it manually whenever we insert a record.

2024-01-10 02:43 UTC, timclark97 requested changes

2024-01-10 02:43 UTC, timclark97 commented on apps/api/src/components/Session/SessionSchema.ts
> +export const weekFromNow = new Date(
You can delete this since it's not used anywhere.

2024-01-10 02:43 UTC, timclark97 commented on apps/api/src/components/Session/SessionSchema.ts
> +  ({ many }): Record<string, Relation<string>> => ({
Is this Record needed?

2024-01-10 02:48 UTC, cstrayer24 commented on apps/api/src/components/Session/SessionSchema.ts
> +  ({ many }): Record<string, Relation<string>> => ({
its so the linter doesnt yell at me

2024-01-11 00:06 UTC, timclark97 commented on apps/api/src/components/Session/SessionSchema.ts
> +  ({ many }): Record<string, Relation<string>> => ({
You should be able to remove it and it will work now.

2024-01-12 13:04 UTC, timclark97 approved these changes

2024-01-12 13:04 UTC, merged