normalizePhoneNum and stytch setup
timclark97/photo-app pull request #6
Opened 2024-01-13 15:58 UTC by cstrayer24

2024-01-17 03:33 UTC, timclark97 requested changes
Good work. I'll pull the branch tomorrow and figure out the linter issue. In the meantime, have some comments.

2024-01-17 03:33 UTC, timclark97 commented on apps/api/package.json
> -    "@types/node": "20.11.0",
Why did this get deleted? I wonder if adding it back could fix the type error in the router.

2024-01-17 03:33 UTC, timclark97 commented on apps/api/src/._server.ts
What is this

2024-01-17 03:33 UTC, timclark97 commented on apps/api/src/components/Authentication/AuthenticationRouter/._index.ts
And this

2024-01-17 03:33 UTC, timclark97 commented on apps/api/src/components/Authentication/AuthenticationRouter/index.ts
> +/*eslint-disable import/order */
You should be able to fix the import order issues. Don't disable it.

2024-01-17 03:33 UTC, timclark97 commented on apps/api/src/components/Authentication/AuthenticationRouter/index.ts
Why put this in an index.ts. Why not have the file name be AuthRouter in the authentication directory

2024-01-17 03:33 UTC, timclark97 commented on apps/api/src/components/Authentication/OTPService/index.ts
Same question about why this is in an index.ts file

2024-01-17 03:33 UTC, timclark97 commented on apps/api/src/components/Authentication/OTPService/index.ts
> +type phoneCodeReturn<Type> = {
As a general rule, types begin with a capital letter. Also naming the generic argument Type may not be the best because lowercase type is a reserved word. The usual name for a generic is just T
```suggestion
type PhoneCodeReturn<T> = {
```

2024-01-17 03:33 UTC, timclark97 commented on apps/api/src/components/Authentication/OTPService/index.ts
> +    throw new Error("missing params for stytch");
This should be an AppError

2024-01-17 03:33 UTC, timclark97 commented on apps/api/src/helpers/normalizePhoneNum.ts
> +const normalizePhoneNum = (unformatted: string) => {
This should throw AppErrors.

2024-01-17 03:33 UTC, timclark97 commented on apps/api/src/server.ts
> +server.register(AuthRoutes, { prefix: "/auth" });
Add an empty space after the route definitions to help visually keep things separated

2024-01-17 03:33 UTC, timclark97 commented on apps/api/src/components/Authentication/AuthenticationRouter/index.ts
> +
Remove extra white space

2024-01-17 03:33 UTC, timclark97 commented on apps/api/src/components/Authentication/AuthenticationRouter/index.ts
> +        res.status(200).send({ method_id: phoneCodeSend.metaData.phone_id });
You don't need to change this, but just so you know, fastify sends a 200 status by default

2024-01-17 03:33 UTC, timclark97 commented on apps/api/src/components/Authentication/OTPService/index.ts
> +export type stytchOTPAuthReq = {
Is this used? As a general rule, don't export something from a file unless it is actually being used somewhere else.

2024-01-17 03:33 UTC, timclark97 commented on apps/api/src/components/Authentication/OTPService/index.ts
> +export { sendPhoneCode, authenticatePhoneCode };
Instead of exporting an object that contains the functions, put the export in front of the functions themselves.

2024-01-17 03:33 UTC, timclark97 commented on apps/api/src/helpers/normalizePhoneNum.ts
We may need to and more phone number related helpers in the future. I would make this file more generic, phoneHelper. And remove the default export.

2024-01-17 13:47 UTC, timclark97 commented on apps/api/src/components/Authentication/AuthenticationRouter/index.ts
> +/*eslint-disable import/order */
I pushed an eslint update to master that should fix the import error you were having

2024-01-20 18:24 UTC, cstrayer24 commented on apps/api/src/components/Authentication/OTPService/index.ts
> +type phoneCodeReturn<Type> = {
noted and fixed

2024-01-20 18:28 UTC, cstrayer24 commented on apps/api/src/components/Authentication/OTPService/index.ts
> +export type stytchOTPAuthReq = {
I was thinking it would need it to be originally but i fixed it

2024-01-20 18:42 UTC, cstrayer24 commented on apps/api/src/components/Authentication/OTPService/index.ts
> +    throw new Error("missing params for stytch");
is there a specific error code you would like me to pass as the second arg I just did 422 which is unprocessesable entity

2024-01-20 18:43 UTC, cstrayer24 commented on apps/api/src/components/Authentication/OTPService/index.ts
> +export { sendPhoneCode, authenticatePhoneCode };
fixed

2024-01-20 18:49 UTC, cstrayer24 commented on apps/api/src/components/Authentication/OTPService/index.ts
the notion notes made it seemed like it was meant to be organized in drectorys so I just did it like this but Ill just assume the last path is meant to be a ts file

2024-01-20 18:56 UTC, cstrayer24 commented on apps/api/src/components/Authentication/AuthenticationRouter/index.ts
> +        res.status(200).send({ method_id: phoneCodeSend.metaData.phone_id });
thank you will keep that in mind

2024-01-20 20:27 UTC, timclark97 requested changes

2024-01-20 20:27 UTC, timclark97 commented on package.json
> +    "stytch": "^10.3.0",
add these dependencies in `apps/api/package.json`

2024-01-20 20:27 UTC, timclark97 commented on apps/api/src/server.ts
> +server.setErrorHandler((e: AppError | Error, req, reply) => {
if you pull master, `e: unknown` should work.

2024-01-20 20:27 UTC, timclark97 commented on apps/api/src/components/Authentication/OTPService.ts.ts
> +import AppError from "@/lib/AppError.js";
Be consistent with your imports.
```suggestion
import authclientStytch from "@/lib/stytch.js";
import { normalizePhoneNum } from "@/helpers/phoneHelper.js";
import AppError from "@/lib/AppError.js";
```

2024-01-20 20:27 UTC, timclark97 commented on apps/api/src/components/Authentication/AuthenticatioRouter.ts
> +import AppError from "../../lib/AppError.js";
```suggestion
import AppError from "@/lib/AppError.js";
```

2024-01-20 20:50 UTC, cstrayer24 commented on apps/api/src/components/Authentication/OTPService.ts.ts
> +import AppError from "@/lib/AppError.js";
My bad the path alias was causing issues

2024-01-21 00:33 UTC, timclark97 commented on package.json
> +    "stytch": "^10.3.0",
Now remove them from this package.json

2024-01-21 13:03 UTC, timclark97 approved these changes
Good work! This is going to be the foundation for a lot of functionality!

2024-01-23 18:05 UTC, merged